// Constants for the app

export const COLORS = {
  GRAY_TEXT_COLOR: "#A0A4A8",
  PRIMARY_COLOR: "#19A5B0",
  BLACK_ICON: "#52575C",
  PAGE_HEADER_BLACK: "#25282B",
  LIGHT_GRAY_BORDER: "#E8E8E8",
  TAG_ORANGE: "#F97B1C",
  WHITE: "#ffffff",
  GRAY_BACKGROUND: "#EDEDED",
  LIGHT_GREEN: "#DEF3F4",
};

export const MOCK_TIME_DELAY_IN_MILLISECONDS = 3000;
